// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irewdybykldmityuxbkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZXdkeWJ5a2xkbWl0eXV4YmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTIwMDIsImV4cCI6MjA2MTA4ODAwMn0.XcWuF65remE1XAug7VXXUFTF0oiHiypdRQPo89goq10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);